FE = (5.6)
GB =(6.7)
ICS =(9.9)
CP =(5.7)
print("---YOUR SCORE---")
print("Foundation English :",FE)
print("General Business :",GB)
print("Introduction to Computer Systems :",ICS)
print("Computer Programming :",CP)